apiVersion: tarasque.crossplane.io/v1alpha1
kind: KafkaBench
metadata:
  name: roundtrip-bench
spec:
  class: org.apache.kafka.trogdor.workload.RoundTripWorkloadSpec
  durationMs: 10000000
  clientNode: node0
  bootstrapServers: kafka.tarasque.svc.cluster.local:9092
  targetMessagesPerSec: 10000
  maxMessages: 150000
  activeTopics:
    test[1-5]:
      numPartitions: 10
      replicationFactor: 3
  providerConfigRef:
    name: example

