apiVersion: v1
kind: Secret
metadata:
  name: example-provider-secret
  namespace: tarasque
type: Opaque
data:
  credentials: dGVzdAo=
---
apiVersion: tarasque.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: example
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: tarasque
      name: example-provider-secret
      key: credentials

