//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2020 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConsumerBenchResultStats) DeepCopyInto(out *ConsumerBenchResultStats) {
	*out = *in
	if in.AssignedPartitions != nil {
		in, out := &in.AssignedPartitions, &out.AssignedPartitions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RecordProcessorStatus != nil {
		in, out := &in.RecordProcessorStatus, &out.RecordProcessorStatus
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConsumerBenchResultStats.
func (in *ConsumerBenchResultStats) DeepCopy() *ConsumerBenchResultStats {
	if in == nil {
		return nil
	}
	out := new(ConsumerBenchResultStats)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KafkaBench) DeepCopyInto(out *KafkaBench) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaBench.
func (in *KafkaBench) DeepCopy() *KafkaBench {
	if in == nil {
		return nil
	}
	out := new(KafkaBench)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KafkaBench) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KafkaBenchList) DeepCopyInto(out *KafkaBenchList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KafkaBench, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaBenchList.
func (in *KafkaBenchList) DeepCopy() *KafkaBenchList {
	if in == nil {
		return nil
	}
	out := new(KafkaBenchList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KafkaBenchList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KafkaBenchObservation) DeepCopyInto(out *KafkaBenchObservation) {
	*out = *in
	out.ProducerStats = in.ProducerStats
	if in.ConsumerStats != nil {
		in, out := &in.ConsumerStats, &out.ConsumerStats
		*out = make(map[string]ConsumerBenchResultStats, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	out.RoundTripStats = in.RoundTripStats
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaBenchObservation.
func (in *KafkaBenchObservation) DeepCopy() *KafkaBenchObservation {
	if in == nil {
		return nil
	}
	out := new(KafkaBenchObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KafkaBenchSpec) DeepCopyInto(out *KafkaBenchSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	if in.ActiveTopics != nil {
		in, out := &in.ActiveTopics, &out.ActiveTopics
		*out = make(map[string]KafkaTopics, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.InactiveTopics != nil {
		in, out := &in.InactiveTopics, &out.InactiveTopics
		*out = make(map[string]KafkaTopics, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ProducerConf != nil {
		in, out := &in.ProducerConf, &out.ProducerConf
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ConsumerConf != nil {
		in, out := &in.ConsumerConf, &out.ConsumerConf
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.CommonClientConf != nil {
		in, out := &in.CommonClientConf, &out.CommonClientConf
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.AdminClientConf != nil {
		in, out := &in.AdminClientConf, &out.AdminClientConf
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaBenchSpec.
func (in *KafkaBenchSpec) DeepCopy() *KafkaBenchSpec {
	if in == nil {
		return nil
	}
	out := new(KafkaBenchSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KafkaBenchStatus) DeepCopyInto(out *KafkaBenchStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaBenchStatus.
func (in *KafkaBenchStatus) DeepCopy() *KafkaBenchStatus {
	if in == nil {
		return nil
	}
	out := new(KafkaBenchStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KafkaTopics) DeepCopyInto(out *KafkaTopics) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaTopics.
func (in *KafkaTopics) DeepCopy() *KafkaTopics {
	if in == nil {
		return nil
	}
	out := new(KafkaTopics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProducerBenchResultStats) DeepCopyInto(out *ProducerBenchResultStats) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProducerBenchResultStats.
func (in *ProducerBenchResultStats) DeepCopy() *ProducerBenchResultStats {
	if in == nil {
		return nil
	}
	out := new(ProducerBenchResultStats)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoundTripBenchResultStats) DeepCopyInto(out *RoundTripBenchResultStats) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoundTripBenchResultStats.
func (in *RoundTripBenchResultStats) DeepCopy() *RoundTripBenchResultStats {
	if in == nil {
		return nil
	}
	out := new(RoundTripBenchResultStats)
	in.DeepCopyInto(out)
	return out
}
